name: secp256k1_cipher
description: Encrypt and decrypt data using secp256k1, This is the High level API build from pointycastle. A fork of secp256k1Cipher.
version: 1.0.0
author: TJ.Campanella<tjcampanella9@gmail.com>
homepage: https://github.com/tjcampanella/secp256k1_cipher

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pointycastle: 3.1.2
  hex: ^0.2.0
  base58check: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
