name: kepler
description: Encrypt and decrypt data using secp256k1, This is the High level API build from pointycastle. A fork of secp256k1Cipher.
version: 1.0.0
homepage: https://github.com/tjcampanella/kepler

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # Newest version of pc doesn't work on web will update once that is fixed.
  pointycastle: 3.1.2
  hex: ^0.2.0
  base58check: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
